# Generated by Django 5.1.7 on 2025-04-23 13:01

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_user_confirmationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmationcode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='confirmationcode',
            name='code',
            field=models.CharField(default=product.models.generate_code, max_length=6),
        ),
    ]
